spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVER}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  liquibase:
    change-log: classpath:db/dbchangelog.yaml
    enabled: true
    default-schema: public
    drop-first: true

  application:
    name: PRODUCTS

  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_SERVER}:8761/eureka/

identity:
  server: ${IDENTITY}