server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true

      routes:
        - id: PRODUCTS
          uri: http://localhost:8081/
          predicates:
            - Path=/products/**

        - id: Seller
          uri: http://localhost:8081/
          predicates:
            - Path=/company/**
          filters:
            - AuthenticationFilter

        - id: User
          uri: http://localhost:8081/
          predicates:
            - Path=/user/**, /admin/**
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: http://localhost:8082/
          predicates:
            - Path=/auth/**, /admin-identity/**
          filters:
            - AuthenticationFilter

  application:
    name: GATEWAY

