server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVER}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:db/dbchangelog-test.yaml
    enabled: true
    default-schema: public
    drop-first: true

  application:
    name: IDENTITY

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_SERVER}:8761/eureka/